[workspace]
resolver = "2"
members = [
 "axl",
 "axl_lib",
 "axl_derive",
]

[workspace.dependencies]
pretty_assertions = "1.4.0"
rstest = "0.18.2"
rstest_reuse = "0.6.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
