env:
  RUST_LOG: info
  TEST_ENV: false
steps:
  - type: package
    env:
      RUST_LOG: trace
      TEST_ENV: true
  - type: lint
  - type: test
  - type: publish
    env:
      RUST_LOG: info
      TEST_ENV: false
