name: Publish Crate
on:
  release:
    types:
      - released
jobs:
  publish-crate:
    uses: pitoniak32/actions/.github/workflows/rust-publish-crate.yml@main
    secrets: 
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
