name: Build & Format & Clippy & Test
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
   ci:
    uses: pitoniak32/actions/.github/workflows/rust-ci.yml@main
